/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import javax.swing.JFileChooser;

/**
 *
 * @author Test
 */
public class UIInicia extends javax.swing.JFrame {

  /**
   * Creates new form UIInicia
   */
  public UIInicia() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    EligeArchivoBoton = new javax.swing.JButton();
    EligeArchivoAreaTexto = new javax.swing.JTextField();
    BusquedaComboBox = new javax.swing.JComboBox<>();
    jLabel1 = new javax.swing.JLabel();
    SalirBoton = new javax.swing.JButton();
    GenerarBoton = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    EligeArchivoBoton.setText("Elegir Archivo");
    EligeArchivoBoton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        EligeArchivoBotonActionPerformed(evt);
      }
    });

    BusquedaComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BFS", "DFS", "A*" }));

    jLabel1.setText("Tipo de Busqueda");

    SalirBoton.setText("Salir");
    SalirBoton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        SalirBotonActionPerformed(evt);
      }
    });

    GenerarBoton.setText("Generar");
    GenerarBoton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        GenerarBotonActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
          .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(EligeArchivoBoton)
              .addComponent(jLabel1))
            .addGap(27, 27, 27)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
              .addComponent(BusquedaComboBox, 0, 187, Short.MAX_VALUE)
              .addComponent(EligeArchivoAreaTexto)))
          .addGroup(layout.createSequentialGroup()
            .addComponent(SalirBoton)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(GenerarBoton)))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(EligeArchivoBoton)
          .addComponent(EligeArchivoAreaTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addComponent(BusquedaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel1))
        .addGap(33, 33, 33)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(SalirBoton)
          .addComponent(GenerarBoton))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void EligeArchivoBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EligeArchivoBotonActionPerformed
    JFileChooser fc = new JFileChooser();
    int seleccion = fc.showOpenDialog(this);
    if (seleccion == JFileChooser.APPROVE_OPTION) {
      EligeArchivoAreaTexto.setText(fc.getSelectedFile().getAbsolutePath());
    }                                                 
  }//GEN-LAST:event_EligeArchivoBotonActionPerformed

  private void SalirBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirBotonActionPerformed
    this.dispose();
  }//GEN-LAST:event_SalirBotonActionPerformed

  private void GenerarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GenerarBotonActionPerformed
    //aqui se llama al bus evento para generar el laberinto debo hacer una funcion que sea escuchada por el procedimiento y se enviara un mensaje que se llama genera laberinto
  }//GEN-LAST:event_GenerarBotonActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(UIInicia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(UIInicia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(UIInicia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(UIInicia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new UIInicia().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JComboBox<String> BusquedaComboBox;
  private javax.swing.JTextField EligeArchivoAreaTexto;
  private javax.swing.JButton EligeArchivoBoton;
  private javax.swing.JButton GenerarBoton;
  private javax.swing.JButton SalirBoton;
  private javax.swing.JLabel jLabel1;
  // End of variables declaration//GEN-END:variables
}
