/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Laberinto.Laberinto;
import java.awt.Color;
import java.awt.GridLayout;
import javax.swing.ImageIcon;
import javax.swing.JButton;


/**
 *
 * @author Test
 */
public class UILaberinto extends javax.swing.JFrame {

  public UILaberinto() {
    initComponents();
    generarLayout();
    generaBotonesMatriz();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jPanelLaberinto = new javax.swing.JPanel();
    jMenuBarLaberinto = new javax.swing.JMenuBar();
    jMenu1 = new javax.swing.JMenu();
    jMenu2 = new javax.swing.JMenu();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    jPanelLaberinto.setAutoscrolls(true);
    jPanelLaberinto.setPreferredSize(new java.awt.Dimension(800, 600));

    javax.swing.GroupLayout jPanelLaberintoLayout = new javax.swing.GroupLayout(jPanelLaberinto);
    jPanelLaberinto.setLayout(jPanelLaberintoLayout);
    jPanelLaberintoLayout.setHorizontalGroup(
      jPanelLaberintoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 800, Short.MAX_VALUE)
    );
    jPanelLaberintoLayout.setVerticalGroup(
      jPanelLaberintoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 600, Short.MAX_VALUE)
    );

    jMenu1.setText("File");
    jMenuBarLaberinto.add(jMenu1);

    jMenu2.setText("Edit");
    jMenuBarLaberinto.add(jMenu2);

    setJMenuBar(jMenuBarLaberinto);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanelLaberinto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanelLaberinto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(UILaberinto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(UILaberinto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(UILaberinto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(UILaberinto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new UILaberinto().setVisible(true);
      }
    });
  }

  private void generaBotonesMatriz() {
    int filas = this.laberinto.getFilas();
    int columnas = this.laberinto.getColumnas();
    boolean img;
    for (int x = 0; x < filas; x++) {
      for (int y = 0; y < columnas; y++) {
        img = false;
        if (this.laberinto.getMatriz().get(x).get(y) == 1) {

          img = !img;
        }
        generarBoton(img,x,y);
      }

    }
  }



  private void generarLayout() {
    GridLayout layout = new GridLayout(this.laberinto.getFilas(), this.laberinto.getColumnas(), 0, 0);
    this.jPanelLaberinto.setLayout(layout);
  }

  private void generarBoton(boolean img,int fila,int columna) {
    JButton boton = new JButton();
    boton.setBorder(null);
    boton.setBorderPainted(false);
    boton.setBackground(Color.DARK_GRAY);
    boton.setName(String.valueOf(fila)+"-"+String.valueOf(columna));
    boton.setBounds(imagenPared.getIconHeight(), imagenPared.getIconWidth(), imagenPared.getIconWidth(), imagenPared.getIconHeight());
    if (img) {
      boton.setIcon(imagenPared);
    }
   
    jPanelLaberinto.add(boton);
  }
  
  ImageIcon imagenPared = new ImageIcon(this.getClass().getResource("Img/pared.PNG"));
  private static Laberinto laberinto;
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JMenu jMenu1;
  private javax.swing.JMenu jMenu2;
  private javax.swing.JMenuBar jMenuBarLaberinto;
  private javax.swing.JPanel jPanelLaberinto;
  // End of variables declaration//GEN-END:variables
}
